name: 'Skywater PDK Libraries Pull Request Merger on Release Branches'
description: 'This is a Pull Request Merger Action that works on repos with release branch structure.'
runs:
  using: "composite"
  steps:
    - name: Export Pull Request ID Name To Environment
      run: echo "PULL_REQUEST_ID=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      shell: bash
    - name: Get Pull Request Patch
      run: wget https://github.com/$GITHUB_REPOSITORY/pull/$PULL_REQUEST_ID.patch
      shell: bash
    - name: Get External Path Name
      run: echo "EXTERNAL_PATH=$(cd $GITHUB_WORKSPACE/../ && pwd)" >> $GITHUB_ENV
      shell: bash
    - name: Move Pull Request Patch out of the working directory
      run: mv $PULL_REQUEST_ID.patch $EXTERNAL_PATH/
      shell: bash
    - name: Run The Pull Request Merger
      run: |
        echo "Running Now! The Pull Request Patch is $EXTERNAL_PATH/$PULL_REQUEST_ID.patch"
        cd $GITHUB_WORKSPACE
        python3 ${{ github.action_path }}/library_patch_submodules.py $EXTERNAL_PATH/$PULL_REQUEST_ID.patch
      shell: bash
    - name: Push Updates to All Branches
      run: git push --force --all
      shell: bash
