name: 'Skywater PDK Libraries Pull Request Merger on Release Branches'
description: 'This is a Pull Request Merger Action that works on repos with release branch structure.'
runs:
  using: "composite"
  steps:
    - name: Get External Path Name
      run: echo "EXTERNAL_PATH=$(cd $GITHUB_WORKSPACE/../ && pwd)" >> $GITHUB_ENV
      shell: bash
    - name: Run The Pull Request Merger
      run: |
        cd $GITHUB_WORKSPACE
        python3 ${{ github.action_path }}/library_multi_pull_requests.py 1 $GITHUB_REPOSITORY 2 ${{ github.token }} 3 $EXTERNAL_PATH
      shell: bash
