name: CI

on: [push]

jobs:
  build:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '50'

      - name: Run The Pull Request Merger
        uses: agorararmard/skywater-pdk-modules-pull-request-backporter-action@main


